language: julia

os:
  - linux
  - osx

env:
  - DEBUG=true
  - DEBUG=false

julia:
  - nightly

notifications:
  email: false

env:
  global:
    - DOCUMENTER_DEBUG=true

after_success:
  - julia -e 'cd(Pkg.dir("LLVM")); Pkg.add("Documenter"); Pkg.checkout("Documenter"); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("LLVM")); Pkg.add("Coverage"); Pkg.checkout("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
