[LLVM]
# which extensions library to use. normally, this is provided by an artifact,
# but if you are using a custom version of LLVM you will need to provide your own,
# e.g., by running `deps/build_local.jl`.
#libLLVMExtra = "/path/to/libLLVMExtra.so"

# whether to enable additional object type checking
#typecheck = "false"

# whether to enable object memory checking. these are expensive checks that keep
# track of allocated objects, whether they are freed correctly, etc.
#memcheck = "false"
